### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by nugoncal** [oracle-devrel/terraform-oci-cloudbricks-mysql-database#2]
Hi all,
Great work with this module!
Could you add defined_tags and freeform_tags ?

**Comment by dralquinta** [comment]
Hi @nugoncal 

Tags will require to have a pre-defined structure in order to give offer generic support to it. As this intends to be as generic as possible, that's why we dropped them from the list. 

We can probably add support for freeform tags in the form of a list being passed on, but I see conflicting issues when dealing with defined tags. Let me know if this is sufficient?

**Comment by nugoncal** [comment]
Hi @dralquinta 

This is a way to provide the flexibility to pass defined_tags we wish to have, without needing to fix which tags are those.
https://github.com/oracle-devrel/terraform-oci-cloudbricks-mysql-database/compare/main...nugoncal:tag?expand=1

It will also work for those who don't want to pass defined_tags. We have this in some other modules of ours.
It's defined_tags we always use in our tagging practice in the Architecture Center Reference Architectures.

Let me know what you think.

**Comment by dralquinta** [comment]
That's actually a very nice fix. Can you trigger the PR to get it approved?

**Comment by dralquinta** [comment]
Closing as issue has been merged to main and released on version v1.0.1
